sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache: pip

jobs:
  include:
#    - stage: integration-test
#      os: linux
#      env:
#      - TEST='NODES_SYNC'
#      script:
#      - sudo pip install -U docker-compose
#      - docker-compose --version
#      - "python3 runtest_nodes_synchronize.py"
#
#    - stage: integration-test
#      os: linux
#      env:
#      - TEST='RUN_10MIN'
#      script:
#      - sudo pip install -U docker-compose
#      - docker-compose --version
#      - "python3 runtest_nodes_10mins.py"

    - stage: integration-test
      os: linux
      env:
      - TEST='SEND_QRL'
      install:
      - sudo pip install -U docker-compose
      - pip3 install -r requirements.txt
      - pip3 -V
      - pip3 freeze
      script:
      - docker-compose --version
      - scripts/wget_qrl_pb2.sh qrl_testing/
      - "python3 runtest_nodes_send_qrl.py"
