sudo: required
dist: trusty
services: docker
language: python
python: 3.5
cache:
  timeout: 600

jobs:
  include:
#    - stage: integration-test
#      os: linux
#      env:
#      - TEST='NODES_SYNC'
#      script:
#      - sudo pip install -U docker-compose | cat
#      - docker-compose --version
#      - "python3 runtest_nodes_synchronize.py"

#    - stage: integration-test
#      os: linux
#      env:
#      - TEST='RUN_10MIN'
#      script:
#      - sudo pip install -U docker-compose | cat
#      - docker-compose --version
#      - "python3 runtest_nodes_10mins.py"

     - stage: integration-test
       os: linux
       before_install:
       - sudo apt-get -y install swig3.0 build-essential software-properties-common
       - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
       - sudo apt-get update
       - sudo apt-get install -y gcc-snapshot gcc-6 g++-6
       - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
       - scripts/cmakesetup.sh
       script: # /home/travis/build/randomshinichi/integration_tests
       - git clone https://github.com/theQRL/QRL.git
       - pip install -r QRL/requirements.txt
       - pip install -e QRL/
       - whoami
       - pwd
       - ls -l
